/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/footer/AppFooter.vue')['default']
    AppNavBar: typeof import('./src/components/navbar/AppNavBar.vue')['default']
    LanguageToggle: typeof import('./src/components/navbar/LanguageToggle.vue')['default']
    LoginFormPanel: typeof import('./src/components/auth/LoginFormPanel.vue')['default']
    LoginLeftPanel: typeof import('./src/components/auth/LoginLeftPanel.vue')['default']
    MobileMenu: typeof import('./src/components/navbar/MobileMenu.vue')['default']
    NavDropdown: typeof import('./src/components/navbar/NavDropdown.vue')['default']
    NavLinks: typeof import('./src/components/navbar/NavLinks.vue')['default']
    NavLogo: typeof import('./src/components/navbar/NavLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
