/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdditionalDataCard: typeof import('./src/components/registration/AdditionalDataCard.vue')['default']
    AdditionalInfoCard: typeof import('./src/components/registration/AdditionalInfoCard.vue')['default']
    AppFooter: typeof import('./src/components/footer/AppFooter.vue')['default']
    AppNavBar: typeof import('./src/components/navbar/AppNavBar.vue')['default']
    AppSidebar: typeof import('./src/components/sidebar/AppSidebar.vue')['default']
    AttachmentsCard: typeof import('./src/components/registration/AttachmentsCard.vue')['default']
    BeneficiaryRegistration: typeof import('./src/components/registration/BeneficiaryRegistration.vue')['default']
    BeneficiaryRequest: typeof import('./src/components/request/BeneficiaryRequest.vue')['default']
    FamilyDetailsCard: typeof import('./src/components/registration/FamilyDetailsCard.vue')['default']
    FinancialObligationsCard: typeof import('./src/components/registration/FinancialObligationsCard.vue')['default']
    FormActionsBar: typeof import('./src/components/registration/FormActionsBar.vue')['default']
    FormStepsBar: typeof import('./src/components/registration/FormStepsBar.vue')['default']
    IncomeDetailsCard: typeof import('./src/components/registration/IncomeDetailsCard.vue')['default']
    LanguageToggle: typeof import('./src/components/navbar/LanguageToggle.vue')['default']
    LoginFormPanel: typeof import('./src/components/auth/LoginFormPanel.vue')['default']
    LoginLeftPanel: typeof import('./src/components/auth/LoginLeftPanel.vue')['default']
    MobileMenu: typeof import('./src/components/navbar/MobileMenu.vue')['default']
    NavDropdown: typeof import('./src/components/navbar/NavDropdown.vue')['default']
    NavLinks: typeof import('./src/components/navbar/NavLinks.vue')['default']
    NavLogo: typeof import('./src/components/navbar/NavLogo.vue')['default']
    PersonalInfoCard: typeof import('./src/components/registration/PersonalInfoCard.vue')['default']
    RegisterFormPanel: typeof import('./src/components/auth/RegisterFormPanel.vue')['default']
    RegistrationSuccess: typeof import('./src/components/registration/RegistrationSuccess.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidationErrorPopup: typeof import('./src/components/registration/ValidationErrorPopup.vue')['default']
    WelcomeCard: typeof import('./src/components/onboarding/WelcomeCard.vue')['default']
  }
}
